# Generated by Django 2.0.6 on 2018-06-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spotlite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mp3url',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
