# Generated by Django 2.0.6 on 2018-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spotlite', '0002_auto_20180626_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='cover',
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.CharField(max_length=128),
        ),
    ]
