# Generated by Django 2.0.6 on 2018-06-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spotlite', '0004_album_mbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='mbid',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
