# Generated by Django 2.0.3 on 2018-06-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_spotlite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
