# Generated by Django 2.0.6 on 2018-06-27 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_spotlite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilebackground',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
